language: python

os:
  - linux

addons:
  apt:
    packages:
      - graphviz
      - python-tk
      - tshark

python:
  - "2.7"
  - "3.6"

#matrix:
#  allow_failures:
#    - python: "3.6"
#before_install:
#  - 
install:
  - pip install -U pytest pytest-cov
  - pip install codecov
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - pytest --cov=./

after_success:
  - codecov
